<?php
require_once __DIR__ . '/tcpdf/TCPDF-main/tcpdf.php';

// Set timezone to Manila
date_default_timezone_set('Asia/Manila');

// Database connection details
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "attendance_monitoring";

// Create connection to the database
$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Get today's date
$todayDate = date('Y-m-d'); // Format: 2025-01-09

// SQL query to fetch today's attendance data
$sql = "SELECT a.employee_number, a.full_name, a.time_in_am, a.time_out_am, a.time_in_pm, a.time_out_pm, a.date_logged 
        FROM attendance a 
        WHERE a.date_logged = '$todayDate'";

$attendanceResult = $conn->query($sql);

// Create a new PDF document
$pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetCreator('Municipality of Lucban');
$pdf->SetAuthor('Admin');
$pdf->SetTitle('Formal Attendance Report');
$pdf->SetSubject('Attendance Records');
$pdf->SetMargins(15, 20, 15);
$pdf->SetAutoPageBreak(true, 15);
$pdf->AddPage();

// Set title
$pdf->SetFont('helvetica', 'B', 16);
$pdf->Cell(0, 10, 'Municipality of Lucban', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 12);
$pdf->Cell(0, 8, 'Attendance Monitoring System', 0, 1, 'C');
$pdf->Cell(0, 8, 'Daily Attendance Report', 0, 1, 'C');
$pdf->Ln(5);

// Add report date
$pdf->SetFont('helvetica', 'I', 10);
$pdf->Cell(0, 8, 'Date: ' . date('F j, Y'), 0, 1, 'R');
$pdf->Ln(5);

// Table header
$pdf->SetFont('helvetica', 'B', 10);
$pdf->SetFillColor(220, 220, 220); // Light grey background
$pdf->Cell(25, 8, 'Employee No.', 1, 0, 'C', true);
$pdf->Cell(50, 8, 'Full Name', 1, 0, 'C', true);
$pdf->Cell(25, 8, 'Time In AM', 1, 0, 'C', true);
$pdf->Cell(25, 8, 'Time Out AM', 1, 0, 'C', true);
$pdf->Cell(25, 8, 'Time In PM', 1, 0, 'C', true);
$pdf->Cell(25, 8, 'Time Out PM', 1, 0, 'C', true);
$pdf->Ln(8);

// Table content
$pdf->SetFont('helvetica', '', 10);
$pdf->SetFillColor(245, 245, 245); // Light alternate row color
$fill = false;

if ($attendanceResult->num_rows > 0) {
    while ($row = $attendanceResult->fetch_assoc()) {
        $pdf->Cell(25, 7, $row['employee_number'], 1, 0, 'C', $fill);
        $pdf->Cell(50, 7, $row['full_name'], 1, 0, 'L', $fill);
        $pdf->Cell(25, 7, $row['time_in_am'], 1, 0, 'C', $fill);
        $pdf->Cell(25, 7, $row['time_out_am'], 1, 0, 'C', $fill);
        $pdf->Cell(25, 7, $row['time_in_pm'], 1, 0, 'C', $fill);
        $pdf->Cell(25, 7, $row['time_out_pm'], 1, 1, 'C', $fill);
        $fill = !$fill; // Toggle row color
    }
} else {
    $pdf->Cell(175, 7, 'No attendance records found for today', 1, 1, 'C', true);
}

// Footer
$pdf->Ln(10);
$pdf->SetFont('helvetica', 'I', 9);
$pdf->Cell(0, 10, 'Generated by the Attendance Monitoring System', 0, 1, 'L');

// Display the PDF in the browser
$pdf->Output('attendance_report.pdf', 'I');
$conn->close();
?>
