<?php
require_once __DIR__ . '/tcpdf/TCPDF-main/tcpdf.php';

// Database connection
require_once 'db_connection.php';



// Get selected records and date filter
$selectedRecords = isset($_POST['selected_records']) ? $_POST['selected_records'] : [];
$startDate = isset($_POST['start_date']) ? $_POST['start_date'] : null;
$endDate = isset($_POST['end_date']) ? $_POST['end_date'] : null;

if (empty($selectedRecords)) {
    echo "No records selected!";
    exit;
}

// Prepare SQL query
$placeholders = implode(',', array_fill(0, count($selectedRecords), '?'));
$sql = "SELECT id, full_name, date_logged, time_in_am, time_out_am, time_in_pm, time_out_pm 
        FROM report 
        WHERE id IN ($placeholders)";

if (!empty($startDate) && !empty($endDate)) {
    $sql .= " AND date_logged BETWEEN ? AND ?";
}

$stmt = $conn->prepare($sql);
$types = str_repeat('s', count($selectedRecords));
$params = $selectedRecords;

if (!empty($startDate) && !empty($endDate)) {
    $types .= 'ss';
    $params[] = $startDate;
    $params[] = $endDate;
}

$stmt->bind_param($types, ...$params);
$stmt->execute();
$result = $stmt->get_result();

// Function to calculate total hours
function calculateTotalHours($in_am, $out_am, $in_pm, $out_pm) {
    $morning_hours = strtotime($out_am) - strtotime($in_am);
    $afternoon_hours = strtotime($out_pm) - strtotime($in_pm);
    return ($morning_hours + $afternoon_hours) / 3600; // Convert seconds to hours
}

// Initialize PDF
$pdf = new TCPDF();
$pdf->SetCreator('Attendance Monitoring System');
$pdf->SetAuthor('Admin');
$pdf->SetTitle('Attendance Report');
$pdf->SetSubject('Attendance Records');

// Set margins and add page
$pdf->SetMargins(10, 15, 10);
$pdf->SetHeaderMargin(5);
$pdf->SetFooterMargin(10);
$pdf->AddPage();

// Header
$pdf->SetFont('helvetica', 'B', 20);
$pdf->Cell(0, 8, 'Attendance Report', 0, 1, 'C');
$pdf->SetFont('helvetica', 'I', 10);
$pdf->Cell(0, 8, 'Generated by Attendance Monitoring System', 0, 1, 'C');
if (!empty($startDate) && !empty($endDate)) {
    $pdf->Cell(0, 8, "Date Range: $startDate to $endDate", 0, 1, 'C');
}
$pdf->Ln(10);

// Process and generate table for each employee
$pdf->SetFont('helvetica', '', 8);
$total_hours_all = 0;
$last_name = '';

if ($result->num_rows > 0) {
    while ($row = $result->fetch_assoc()) {
        // Calculate total hours
        $total_hours = calculateTotalHours($row['time_in_am'], $row['time_out_am'], $row['time_in_pm'], $row['time_out_pm']);
        $total_hours_all += $total_hours;

        // Add employee name above the table
        if ($row['full_name'] !== $last_name) {
            $pdf->Ln(5);
            $pdf->SetFont('helvetica', 'B', 12);
            $pdf->Cell(0, 8, '' . $row['full_name'], 0, 1, 'C');
            $last_name = $row['full_name'];

            // Table Header
            $pdf->SetFont('helvetica', 'B', 9);
            $pdf->SetFillColor(220, 220, 220);
            $headers = ['Date Logged', 'In AM', 'Out AM', 'In PM', 'Out PM', 'Total Hours'];
            $widths = [30, 25, 25, 25, 25, 30];

            // Calculate total width of table for centering
            $total_width = array_sum($widths);
            $pdf->SetX((210 - $total_width) / 2); // Center the table
            foreach ($headers as $i => $header) {
                $pdf->Cell($widths[$i], 8, $header, 1, 0, 'C', true);
            }
            $pdf->Ln();
        }

        // Table row
        $pdf->SetFont('helvetica', '', 8);
        $pdf->SetFillColor(245, 245, 245);
        $fill = false;

        // Center each cell content
        $pdf->SetX((210 - $total_width) / 2); // Center the row cells
        $pdf->Cell(30, 6, $row['date_logged'], 1, 0, 'C', $fill);
        $pdf->Cell(25, 6, $row['time_in_am'], 1, 0, 'C', $fill);
        $pdf->Cell(25, 6, $row['time_out_am'], 1, 0, 'C', $fill);
        $pdf->Cell(25, 6, $row['time_in_pm'], 1, 0, 'C', $fill);
        $pdf->Cell(25, 6, $row['time_out_pm'], 1, 0, 'C', $fill);
        $pdf->Cell(30, 6, number_format($total_hours, 2) . ' hrs', 1, 1, 'C', $fill);
    }
} else {
    $pdf->Cell(0, 10, 'No records found.', 1, 1, 'C');
}

// Total hours footer
$pdf->Ln(10);
$pdf->SetFont('helvetica', 'B', 10);
$pdf->SetTextColor(255, 0, 0);
$pdf->Cell(0, 10, 'Total Hours: ' . number_format($total_hours_all, 2) . ' hours', 0, 1, 'R');

// Output PDF
$pdf->Output('attendance_report.pdf', 'I');
$conn->close();
?>
